/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class MangHinhChao extends javax.swing.JDialog {

    /**
     * Creates new form MangHinhChao
     */
    public MangHinhChao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Load();
//        jProgressBar1.setForeground(Color.blue); //chữ
//        jProgressBar1.put("ProgressBar.foreground", Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNenChinh = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblnen1 = new javax.swing.JLabel();
        lblnen4 = new javax.swing.JLabel();
        lblnen3 = new javax.swing.JLabel();
        lblnen2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblnen5 = new javax.swing.JLabel();
        lblnen6 = new javax.swing.JLabel();

        lblNenChinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NenChao.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 538, 24));

        lblnen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hello.gif"))); // NOI18N
        getContentPane().add(lblnen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 70, 90));

        lblnen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ChaoMung.gif"))); // NOI18N
        getContentPane().add(lblnen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        lblnen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ChaoMung.gif"))); // NOI18N
        getContentPane().add(lblnen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        lblnen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ChaoMung.gif"))); // NOI18N
        getContentPane().add(lblnen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Chào Mừng Các Bạn Đến Với Ứng Dụng Quản Lý");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 480, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ký Túc Xá Trường Đại Học HS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Design by: Hưng & Sỹ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        lblnen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hello.gif"))); // NOI18N
        getContentPane().add(lblnen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 90));

        lblnen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hello.gif"))); // NOI18N
        getContentPane().add(lblnen6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 70, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MangHinhChao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MangHinhChao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MangHinhChao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MangHinhChao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MangHinhChao dialog = new MangHinhChao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblNenChinh;
    private javax.swing.JLabel lblnen1;
    private javax.swing.JLabel lblnen2;
    private javax.swing.JLabel lblnen3;
    private javax.swing.JLabel lblnen4;
    private javax.swing.JLabel lblnen5;
    private javax.swing.JLabel lblnen6;
    // End of variables declaration//GEN-END:variables
    
    public void Load() {
        this.setLocationRelativeTo(null);
        new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int value = jProgressBar1.getValue();
                if (value < jProgressBar1.getMaximum()) {
                    jProgressBar1.setValue(value + 1);
                } else {
                    MangHinhChao.this.dispose();
                }
            }
        }).start();
    }
    
}
